import { FingerState, SignType } from '../types';

export interface AlphabetLetterDefinition {
  label: string;
  type: SignType;
  requiredHandCount: number;
  minimumConfidence: number;
  expectedOrientation: string;
  expectedFingerStates: {
    thumb: FingerState;
    index: FingerState;
    middle: FingerState;
    ring: FingerState;
    pinky: FingerState;
  };
  description: string;
  tips: string;
  temporalRequirements: {
    minFrames: number;
    requiresMotion?: boolean;
    motionDescription?: string;
  };
}

export const ASL_ALPHABET_LETTERS = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'W', 'X', 'Y', 'Z',
] as const;

export type ASLAlphabetLetter = typeof ASL_ALPHABET_LETTERS[number];

export const STATIC_ALPHABET_LETTERS: ASLAlphabetLetter[] = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
  'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'W', 'X', 'Y',
];

export const DYNAMIC_ALPHABET_LETTERS: ASLAlphabetLetter[] = ['J', 'Z'];

export const ASL_ALPHABET_DEFINITIONS: Record<ASLAlphabetLetter, AlphabetLetterDefinition> = {
  A: {
    label: 'A',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'OPEN', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Fingers curled into palm; thumb straight upright along the side of index finger.',
    tips: 'Do not tuck thumb across fingers (that is S). Keep thumb alongside.',
    temporalRequirements: { minFrames: 5 },
  },
  B: {
    label: 'B',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'OPEN', pinky: 'OPEN' },
    description: 'Four fingers upright and touching; thumb folded flat across palm.',
    tips: 'Keep four fingers upright together and thumb tucked across lower palm.',
    temporalRequirements: { minFrames: 5 },
  },
  C: {
    label: 'C',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'side',
    expectedFingerStates: { thumb: 'PARTIAL', index: 'PARTIAL', middle: 'PARTIAL', ring: 'PARTIAL', pinky: 'PARTIAL' },
    description: 'All fingers curved into a C-shape matching the letter profile.',
    tips: 'Hold hand in side profile so camera clearly sees curved arch.',
    temporalRequirements: { minFrames: 5 },
  },
  D: {
    label: 'D',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'PARTIAL', index: 'OPEN', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index finger straight up; middle, ring, pinky touch thumb forming an O at the base.',
    tips: 'Only index points straight up. Middle touches thumb tip.',
    temporalRequirements: { minFrames: 5 },
  },
  E: {
    label: 'E',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.70,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'All fingers tightly curled down with fingertips resting along the top of thumb.',
    tips: 'Fingertips curl tightly downward toward palm; thumb tucked horizontally below.',
    temporalRequirements: { minFrames: 5 },
  },
  F: {
    label: 'F',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'PARTIAL', index: 'PARTIAL', middle: 'OPEN', ring: 'OPEN', pinky: 'OPEN' },
    description: 'Index tip touches thumb tip forming circle; middle, ring, pinky fan straight up.',
    tips: 'Opposite of D: index touches thumb while other 3 fingers stay upright.',
    temporalRequirements: { minFrames: 5 },
  },
  G: {
    label: 'G',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'side',
    expectedFingerStates: { thumb: 'OPEN', index: 'OPEN', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index and thumb parallel pointing horizontally; middle, ring, pinky folded.',
    tips: 'Point index finger horizontally across body with thumb parallel.',
    temporalRequirements: { minFrames: 5 },
  },
  H: {
    label: 'H',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'side',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index and middle fingers extended together horizontally; thumb tucked.',
    tips: 'Fingers horizontal together, palm facing toward yourself.',
    temporalRequirements: { minFrames: 5 },
  },
  I: {
    label: 'I',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.76,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'OPEN' },
    description: 'Pinky finger straight up; thumb folded across curled index, middle, and ring.',
    tips: 'Only pinky extends; ensure pinky is upright.',
    temporalRequirements: { minFrames: 5 },
  },
  J: {
    label: 'J',
    type: 'DYNAMIC',
    requiredHandCount: 1,
    minimumConfidence: 0.75,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'OPEN' },
    description: 'Start in "I" handshape (pinky up) and trace a downward hook/curve like the letter J.',
    tips: 'Hold pinky up, then trace a downward and swooping hook motion.',
    temporalRequirements: { minFrames: 8, requiresMotion: true, motionDescription: 'Downward curved J-swoop with pinky' },
  },
  K: {
    label: 'K',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'OPEN', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index upright, middle pointing slightly forward; thumb rests upright between them.',
    tips: 'Thumb knuckle wedges between index and middle fingers.',
    temporalRequirements: { minFrames: 5 },
  },
  L: {
    label: 'L',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.78,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'OPEN', index: 'OPEN', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index finger straight up, thumb extended sideways forming right-angle L.',
    tips: 'Classic L shape; other 3 fingers curled into palm.',
    temporalRequirements: { minFrames: 5 },
  },
  M: {
    label: 'M',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.70,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Fingers folded over thumb; thumb peeks out between ring and pinky fingers.',
    tips: 'Thumb sits under the first three fingers (index, middle, ring).',
    temporalRequirements: { minFrames: 5 },
  },
  N: {
    label: 'N',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.70,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Thumb tucked under index and middle fingers, peeking out between middle and ring.',
    tips: 'Similar to M, but thumb peeks between middle and ring.',
    temporalRequirements: { minFrames: 5 },
  },
  O: {
    label: 'O',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.75,
    expectedOrientation: 'side',
    expectedFingerStates: { thumb: 'PARTIAL', index: 'PARTIAL', middle: 'PARTIAL', ring: 'PARTIAL', pinky: 'PARTIAL' },
    description: 'All fingertips touch thumb tip forming a closed circle/oval.',
    tips: 'Fingertips meet thumb tip with visible circular opening.',
    temporalRequirements: { minFrames: 5 },
  },
  P: {
    label: 'P',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'down',
    expectedFingerStates: { thumb: 'OPEN', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'K-handshape pointing downward; index horizontal, middle pointing down.',
    tips: 'Downside-down K; wrist tilts downward.',
    temporalRequirements: { minFrames: 5 },
  },
  Q: {
    label: 'Q',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'down',
    expectedFingerStates: { thumb: 'OPEN', index: 'OPEN', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'G-handshape pointing downward; index and thumb pointing toward floor.',
    tips: 'Like G pointing straight down toward the ground.',
    temporalRequirements: { minFrames: 5 },
  },
  R: {
    label: 'R',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.76,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index and middle fingers crossed like good-luck fingers; others curled.',
    tips: 'Middle finger crosses over the front of index finger.',
    temporalRequirements: { minFrames: 5 },
  },
  S: {
    label: 'S',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.74,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Tight fist with thumb folded horizontally across all fingers.',
    tips: 'Thumb crosses across the front of fingers (unlike A where thumb is at the side).',
    temporalRequirements: { minFrames: 5 },
  },
  T: {
    label: 'T',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Thumb tucked under index finger only, peeking out between index and middle.',
    tips: 'Only index finger sits on top of thumb.',
    temporalRequirements: { minFrames: 5 },
  },
  U: {
    label: 'U',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.76,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index and middle fingers upright and touching each other tightly; thumb across ring/pinky.',
    tips: 'Keep index and middle tightly pressed together (unlike V which is spread).',
    temporalRequirements: { minFrames: 5 },
  },
  V: {
    label: 'V',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.78,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index and middle fingers extended apart in a V; others curled.',
    tips: 'Visible V spread between index and middle fingers.',
    temporalRequirements: { minFrames: 5 },
  },
  W: {
    label: 'W',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.78,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'OPEN', ring: 'OPEN', pinky: 'CLOSED' },
    description: 'Index, middle, and ring fingers spread upright; thumb holds pinky down.',
    tips: 'Three middle fingers spread upward forming W.',
    temporalRequirements: { minFrames: 5 },
  },
  X: {
    label: 'X',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.72,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'PARTIAL', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Index finger hooked like a pirate hook; other fingers curled with thumb across.',
    tips: 'Bend index finger at second knuckle into a prominent hook.',
    temporalRequirements: { minFrames: 5 },
  },
  Y: {
    label: 'Y',
    type: 'STATIC',
    requiredHandCount: 1,
    minimumConfidence: 0.78,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'OPEN', index: 'CLOSED', middle: 'CLOSED', ring: 'CLOSED', pinky: 'OPEN' },
    description: 'Thumb and pinky extended outward; index, middle, and ring curled (hang loose / shaka).',
    tips: 'Thumb and pinky point in opposite directions.',
    temporalRequirements: { minFrames: 5 },
  },
  Z: {
    label: 'Z',
    type: 'DYNAMIC',
    requiredHandCount: 1,
    minimumConfidence: 0.75,
    expectedOrientation: 'facing_camera',
    expectedFingerStates: { thumb: 'CLOSED', index: 'OPEN', middle: 'CLOSED', ring: 'CLOSED', pinky: 'CLOSED' },
    description: 'Extend index finger and trace a Z in the air (horizontal right, diagonal down-left, horizontal right).',
    tips: 'Point index finger forward and trace the zig-zag Z in the air.',
    temporalRequirements: { minFrames: 10, requiresMotion: true, motionDescription: 'Z zig-zag trajectory with index finger' },
  },
};
